
package ar.com.educacionit.ws.soap.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ar.com.educacionit.ws.soap.interfaces.ObjectFactory;
import ar.com.educacionit.ws.soap.interfaces.Producto;
import ar.com.educacionit.ws.soap.interfaces.ProductoRequestDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductoWS", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductoWS {


    /**
     * 
     * @return
     *     returns java.util.List<ar.com.educacionit.ws.soap.interfaces.Producto>
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodos", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.soap.interfaces.ObtenerTodos")
    @ResponseWrapper(localName = "obtenerTodosResponse", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.soap.interfaces.ObtenerTodosResponse")
    @Action(input = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerTodosRequest", output = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerTodosResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerTodos/Fault/InternalServerError")
    })
    public List<Producto> obtenerTodos()
        throws InternalServerError
    ;

    /**
     * 
     * @param id
     * @return
     *     returns ar.com.educacionit.ws.soap.interfaces.Producto
     * @throws InternalServerError
     * @throws ProductoNoExisteException
     */
    @WebMethod
    @WebResult(name = "miProducto", targetNamespace = "")
    @RequestWrapper(localName = "obtenerProductoPorCodigo", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.soap.interfaces.ObtenerProductoPorCodigo")
    @ResponseWrapper(localName = "obtenerProductoPorCodigoResponse", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.soap.interfaces.ObtenerProductoPorCodigoResponse")
    @Action(input = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerProductoPorCodigoRequest", output = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerProductoPorCodigoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerProductoPorCodigo/Fault/InternalServerError"),
        @FaultAction(className = ProductoNoExisteException.class, value = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/obtenerProductoPorCodigo/Fault/ProductoNoExisteException")
    })
    public Producto obtenerProductoPorCodigo(
        @WebParam(name = "id", targetNamespace = "")
        Long id)
        throws InternalServerError, ProductoNoExisteException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.educacionit.ws.soap.interfaces.Producto
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearProducto", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.soap.interfaces.CrearProducto")
    @ResponseWrapper(localName = "crearProductoResponse", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.soap.interfaces.CrearProductoResponse")
    @Action(input = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/crearProductoRequest", output = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/crearProductoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://interfaces.soap.ws.educacionit.com.ar/ProductoWS/crearProducto/Fault/InternalServerError")
    })
    public Producto crearProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        ProductoRequestDTO arg0)
        throws InternalServerError
    ;

}
