
package ar.com.educacionit.ws.soap.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProductoNoExisteException", targetNamespace = "http://interfaces.soap.ws.educacionit.com.ar/")
public class ProductoNoExisteException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ar.com.educacionit.ws.soap.interfaces.ProductoNoExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProductoNoExisteException(String message, ar.com.educacionit.ws.soap.interfaces.ProductoNoExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProductoNoExisteException(String message, ar.com.educacionit.ws.soap.interfaces.ProductoNoExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ar.com.educacionit.ws.soap.interfaces.ProductoNoExisteException
     */
    public ar.com.educacionit.ws.soap.interfaces.ProductoNoExisteException getFaultInfo() {
        return faultInfo;
    }

}
